default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number
    build_app(scheme: "Runner")
    upload_to_testflight
  end
end

platform :android do
  desc "Build Android release"
  lane :release do
    gradle(task: 'assemble', build_type: 'Release')
    # You can add supply to upload to Play Store
  end
end
