"""add_prince_ai_models

Revision ID: aa053d676dcc
Revises: 
Create Date: 2025-10-26 22:17:08.927959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa053d676dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name', 'cache_key', name='uq_api_cache_key')
    )
    op.create_index(op.f('ix_api_cache_api_name'), 'api_cache', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_cache_cache_key'), 'api_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_api_cache_id'), 'api_cache', ['id'], unique=False)
    op.create_table('api_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_api_name'), 'api_call_logs', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_call_logs_category'), 'api_call_logs', ['category'], unique=False)
    op.create_index(op.f('ix_api_call_logs_id'), 'api_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_timestamp'), 'api_call_logs', ['timestamp'], unique=False)
    op.create_table('strategy_performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('market_condition', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_profit', sa.Float(), nullable=False),
    sa.Column('avg_loss', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_performance_id'), 'strategy_performance', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_performance_market_condition'), 'strategy_performance', ['market_condition'], unique=False)
    op.create_index(op.f('ix_strategy_performance_strategy_name'), 'strategy_performance', ['strategy_name'], unique=False)
    op.create_table('prince_signal_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('signal_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_profit_pct', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('prince_message', sa.String(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prince_signal_alerts_created_at'), 'prince_signal_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_prince_signal_alerts_expires_at'), 'prince_signal_alerts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_prince_signal_alerts_id'), 'prince_signal_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_prince_signal_alerts_market'), 'prince_signal_alerts', ['market'], unique=False)
    op.create_index(op.f('ix_prince_signal_alerts_symbol'), 'prince_signal_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_prince_signal_alerts_user_id'), 'prince_signal_alerts', ['user_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN - skip for SQLite or handle separately
    # For SQLite, this change would require recreating the table, which is complex
    # If using PostgreSQL, uncomment the following:
    # op.alter_column('refresh_tokens', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    
    # For SQLite: Check connection and skip if SQLite
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    if bind.dialect.name != 'sqlite':
        # Only alter for non-SQLite databases
        op.alter_column('refresh_tokens', 'user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(length=36),
                   existing_nullable=False)
    else:
        # For SQLite, skip - assume user_id is already String if table exists
        # This is a limitation of SQLite's ALTER TABLE support
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN - skip for SQLite
    from sqlalchemy import inspect
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('refresh_tokens', 'user_id',
                   existing_type=sa.String(length=36),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
    op.drop_index(op.f('ix_prince_signal_alerts_user_id'), table_name='prince_signal_alerts')
    op.drop_index(op.f('ix_prince_signal_alerts_symbol'), table_name='prince_signal_alerts')
    op.drop_index(op.f('ix_prince_signal_alerts_market'), table_name='prince_signal_alerts')
    op.drop_index(op.f('ix_prince_signal_alerts_id'), table_name='prince_signal_alerts')
    op.drop_index(op.f('ix_prince_signal_alerts_expires_at'), table_name='prince_signal_alerts')
    op.drop_index(op.f('ix_prince_signal_alerts_created_at'), table_name='prince_signal_alerts')
    op.drop_table('prince_signal_alerts')
    op.drop_index(op.f('ix_strategy_performance_strategy_name'), table_name='strategy_performance')
    op.drop_index(op.f('ix_strategy_performance_market_condition'), table_name='strategy_performance')
    op.drop_index(op.f('ix_strategy_performance_id'), table_name='strategy_performance')
    op.drop_table('strategy_performance')
    op.drop_index(op.f('ix_api_call_logs_timestamp'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_category'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_api_name'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    op.drop_index(op.f('ix_api_cache_id'), table_name='api_cache')
    op.drop_index(op.f('ix_api_cache_cache_key'), table_name='api_cache')
    op.drop_index(op.f('ix_api_cache_api_name'), table_name='api_cache')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
